# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f386fc03bdddc832f3c9a7b7bfd02e6078021b7b9a495fd18e8cfe63c078693a06eeb25169c4e23265cecc2c2bf5c62609408d026da53572f2fa25a8c00e9884

test:
  secret_key_base: d5583bd9ef55f651a5ed5d83a45bddff2fa0f2704fc5532b9721f7c5e4bfa12020a1a111c072a90f52362cd13b7263d853fb4d9ca52bb6e928ee0283f94b1ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
